export const IMGS_REQUEST = 'IMGS_REQUEST';
export const IMGS_SUCCESS = 'IMGS_SUCCESS';
export const IMGS_FAIL = 'IMGS_FAIL';

export const IMGS_ACTIVE_INTERVAL = 'IMGS_ACTIVE_INTERVAL';
export const IMGS_ACTIVE_INTERVAL_SUCCESS = 'IMGS_ACTIVE_INTERVAL_SUCCESS';

export const IMGS_UPDATE_INTERVAL = 'IMGS_UPDATE_INTERVAL';
export const IMGS_REMOVE_INTERVAL = 'IMGS_REMOVE_INTERVAL';

export const IMG_SELECTED = 'IMG_SELECTED';
export const IMG_DESELECT = 'IMG_DESELECT';
